In [1]:
import cv2
import pandas as pd
import numpy as np


In [2]:
import requests

In [3]:
#import requests

url = "https://free-images-api.p.rapidapi.com/images/dog"

headers = {
	"X-RapidAPI-Key": "cf89039f90mshe45f551b87b88dep1d0f46jsn72c60de8d865",
	"X-RapidAPI-Host": "free-images-api.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'results': [{'image': 'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww', 'by': 'https://unsplash.com/plus?referrer=%2Fphotos%2Fa-black-and-white-dog-laying-on-top-of-a-white-floor-GjUSnrVpt_0', 'source': 'https://unsplash.com', 'diffrentSizes': ['https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid

In [4]:
response.json()

{'results': [{'image': 'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww',
   'by': 'https://unsplash.com/plus?referrer=%2Fphotos%2Fa-black-and-white-dog-laying-on-top-of-a-white-floor-GjUSnrVpt_0',
   'source': 'https://unsplash.com',
   'diffrentSizes': ['https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww',
    'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww',
    'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww',
    'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?w=400&auto=format&fit=crop&q=6

In [5]:
from pandas import json_normalize

In [6]:
dog = json_normalize(response.json(),record_path='results')

In [7]:
#import requests

url = "https://free-images-api.p.rapidapi.com/images/cat"

headers = {
	"X-RapidAPI-Key": "cf89039f90mshe45f551b87b88dep1d0f46jsn72c60de8d865",
	"X-RapidAPI-Host": "free-images-api.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'results': [{'image': 'https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0fGVufDB8fDB8fHww', 'by': 'https://unsplash.com/plus?referrer=%2Fphotos%2Fa-cat-sitting-on-top-of-a-green-cushion-JticgxGJ95c', 'source': 'https://unsplash.com', 'diffrentSizes': ['https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8

In [8]:
cat = pd.json_normalize(response.json(),record_path='results')

In [9]:
#import requests

url = "https://free-images-api.p.rapidapi.com/images/elephant"

headers = {
	"X-RapidAPI-Key": "cf89039f90mshe45f551b87b88dep1d0f46jsn72c60de8d865",
	"X-RapidAPI-Host": "free-images-api.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'results': [{'image': 'https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D', 'by': 'https://unsplash.com/plus?referrer=%2Fphotos%2Fa-large-elephant-walking-across-a-dry-grass-field-wGzvvuNIMz0', 'source': 'https://unsplash.com', 'diffrentSizes': ['https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D', 'https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D', 'https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D', 'https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?w=400&auto=for

In [10]:
elephant = pd.json_normalize(response.json(),record_path='results')

In [11]:
#import requests

url = "https://free-images-api.p.rapidapi.com/images/parrot"

headers = {
	"X-RapidAPI-Key": "cf89039f90mshe45f551b87b88dep1d0f46jsn72c60de8d865",
	"X-RapidAPI-Host": "free-images-api.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'results': [{'image': 'https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFycm90fGVufDB8fDB8fHww', 'by': 'https://unsplash.com/plus?referrer=%2Fphotos%2Fa-bird-with-a-nut-in-its-mouth-qZXMqoGIbCc', 'source': 'https://unsplash.com', 'diffrentSizes': ['https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFycm90fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFycm90fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFycm90fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxM

In [12]:
parrot = pd.json_normalize(response.json(),record_path='results')

In [13]:
#import requests

url = "https://free-images-api.p.rapidapi.com/images/cow"

headers = {
	"X-RapidAPI-Key": "cf89039f90mshe45f551b87b88dep1d0f46jsn72c60de8d865",
	"X-RapidAPI-Host": "free-images-api.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'results': [{'image': 'https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww', 'by': 'https://unsplash.com/plus?referrer=%2Fphotos%2Fherd-of-young-white-cows-on-green-meadow-hxVkNG-yeuo', 'source': 'https://unsplash.com', 'diffrentSizes': ['https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww', 'https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB

In [14]:
cow = pd.json_normalize(response.json(),record_path='results')

In [15]:
dog

image  \
0   https://plus.unsplash.com/premium_photo-167754...   
1   https://images.unsplash.com/photo-153028170054...   
2   https://images.unsplash.com/photo-151784984553...   
3   https://images.unsplash.com/photo-1552053831-7...   
4   https://plus.unsplash.com/premium_photo-167647...   
5   https://images.unsplash.com/photo-1561037404-6...   
6   https://images.unsplash.com/photo-1543466835-0...   
7   https://images.unsplash.com/photo-158730000338...   
8   https://plus.unsplash.com/premium_photo-168609...   
9   https://images.unsplash.com/photo-158667126773...   
10  https://images.unsplash.com/photo-153715162574...   
11  https://images.unsplash.com/photo-158894321134...   
12  https://plus.unsplash.com/premium_photo-167872...   
13  https://images.unsplash.com/photo-158351260380...   
14  https://images.unsplash.com/photo-158333713041...   
15  https://images.unsplash.com/photo-147788421336...   
16  https://plus.unsplash.com/premium_photo-166629...   
17  https://images.unsplash.com/photo-157620183610...   
18  https://images.unsplash.com/photo-159649278453...   
19  https://images.unsplash.com/photo-1560807707-8...   

                                                   by                source  \
0   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
1                          https://unsplash.com/@o5ky  https://unsplash.com   
2                https://unsplash.com/@charlesdeluvio  https://unsplash.com   
3                 https://unsplash.com/@richardbrutyo  https://unsplash.com   
4   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
5                 https://unsplash.com/@victor_vector  https://unsplash.com   
6            https://unsplash.com/@marliesestreefland  https://unsplash.com   
7                      https://unsplash.com/@paulinel  https://unsplash.com   
8   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
9                   https://unsplash.com/@taylorkopel  https://unsplash.com   
10                     https://unsplash.com/@alvannee  https://unsplash.com   
11                     https://unsplash.com/@ralu_gal  https://unsplash.com   
12  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
13                   https://unsplash.com/@karsten116  https://unsplash.com   
14                   https://unsplash.com/@karsten116  https://unsplash.com   
15                https://unsplash.com/@justinveenema  https://unsplash.com   
16  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
17                    https://unsplash.com/@castillcc  https://unsplash.com   
18                    https://unsplash.com/@whoisperi  https://unsplash.com   
19                       https://unsplash.com/@_redo_  https://unsplash.com   

                                        diffrentSizes  \
0   [https://plus.unsplash.com/premium_photo-16775...   
1   [https://images.unsplash.com/photo-15302817005...   
2   [https://images.unsplash.com/photo-15178498455...   
3   [https://images.unsplash.com/photo-1552053831-...   
4   [https://plus.unsplash.com/premium_photo-16764...   
5   [https://images.unsplash.com/photo-1561037404-...   
6   [https://images.unsplash.com/photo-1543466835-...   
7   [https://images.unsplash.com/photo-15873000033...   
8   [https://plus.unsplash.com/premium_photo-16860...   
9   [https://images.unsplash.com/photo-15866712677...   
10  [https://images.unsplash.com/photo-15371516257...   
11  [https://images.unsplash.com/photo-15889432113...   
12  [https://plus.unsplash.com/premium_photo-16787...   
13  [https://images.unsplash.com/photo-15835126038...   
14  [https://images.unsplash.com/photo-15833371304...   
15  [https://images.unsplash.com/photo-14778842133...   
16  [https://plus.unsplash.com/premium_photo-16662...   
17  [https://images.unsplash.com/photo-15762018361...   
18  [https://images.unsplash.com/photo-15964927845...   
19  [https://images.unsplash.com/photo-1560807707-

In [16]:
import urllib.request

In [17]:
dog

image  \
0   https://plus.unsplash.com/premium_photo-167754...   
1   https://images.unsplash.com/photo-153028170054...   
2   https://images.unsplash.com/photo-151784984553...   
3   https://images.unsplash.com/photo-1552053831-7...   
4   https://plus.unsplash.com/premium_photo-167647...   
5   https://images.unsplash.com/photo-1561037404-6...   
6   https://images.unsplash.com/photo-1543466835-0...   
7   https://images.unsplash.com/photo-158730000338...   
8   https://plus.unsplash.com/premium_photo-168609...   
9   https://images.unsplash.com/photo-158667126773...   
10  https://images.unsplash.com/photo-153715162574...   
11  https://images.unsplash.com/photo-158894321134...   
12  https://plus.unsplash.com/premium_photo-167872...   
13  https://images.unsplash.com/photo-158351260380...   
14  https://images.unsplash.com/photo-158333713041...   
15  https://images.unsplash.com/photo-147788421336...   
16  https://plus.unsplash.com/premium_photo-166629...   
17  https://images.unsplash.com/photo-157620183610...   
18  https://images.unsplash.com/photo-159649278453...   
19  https://images.unsplash.com/photo-1560807707-8...   

                                                   by                source  \
0   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
1                          https://unsplash.com/@o5ky  https://unsplash.com   
2                https://unsplash.com/@charlesdeluvio  https://unsplash.com   
3                 https://unsplash.com/@richardbrutyo  https://unsplash.com   
4   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
5                 https://unsplash.com/@victor_vector  https://unsplash.com   
6            https://unsplash.com/@marliesestreefland  https://unsplash.com   
7                      https://unsplash.com/@paulinel  https://unsplash.com   
8   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
9                   https://unsplash.com/@taylorkopel  https://unsplash.com   
10                     https://unsplash.com/@alvannee  https://unsplash.com   
11                     https://unsplash.com/@ralu_gal  https://unsplash.com   
12  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
13                   https://unsplash.com/@karsten116  https://unsplash.com   
14                   https://unsplash.com/@karsten116  https://unsplash.com   
15                https://unsplash.com/@justinveenema  https://unsplash.com   
16  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
17                    https://unsplash.com/@castillcc  https://unsplash.com   
18                    https://unsplash.com/@whoisperi  https://unsplash.com   
19                       https://unsplash.com/@_redo_  https://unsplash.com   

                                        diffrentSizes  \
0   [https://plus.unsplash.com/premium_photo-16775...   
1   [https://images.unsplash.com/photo-15302817005...   
2   [https://images.unsplash.com/photo-15178498455...   
3   [https://images.unsplash.com/photo-1552053831-...   
4   [https://plus.unsplash.com/premium_photo-16764...   
5   [https://images.unsplash.com/photo-1561037404-...   
6   [https://images.unsplash.com/photo-1543466835-...   
7   [https://images.unsplash.com/photo-15873000033...   
8   [https://plus.unsplash.com/premium_photo-16860...   
9   [https://images.unsplash.com/photo-15866712677...   
10  [https://images.unsplash.com/photo-15371516257...   
11  [https://images.unsplash.com/photo-15889432113...   
12  [https://plus.unsplash.com/premium_photo-16787...   
13  [https://images.unsplash.com/photo-15835126038...   
14  [https://images.unsplash.com/photo-15833371304...   
15  [https://images.unsplash.com/photo-14778842133...   
16  [https://plus.unsplash.com/premium_photo-16662...   
17  [https://images.unsplash.com/photo-15762018361...   
18  [https://images.unsplash.com/photo-15964927845...   
19  [https://images.unsplash.com/photo-1560807707-

In [18]:
dog['image']

0     https://plus.unsplash.com/premium_photo-167754...
1     https://images.unsplash.com/photo-153028170054...
2     https://images.unsplash.com/photo-151784984553...
3     https://images.unsplash.com/photo-1552053831-7...
4     https://plus.unsplash.com/premium_photo-167647...
5     https://images.unsplash.com/photo-1561037404-6...
6     https://images.unsplash.com/photo-1543466835-0...
7     https://images.unsplash.com/photo-158730000338...
8     https://plus.unsplash.com/premium_photo-168609...
9     https://images.unsplash.com/photo-158667126773...
10    https://images.unsplash.com/photo-153715162574...
11    https://images.unsplash.com/photo-158894321134...
12    https://plus.unsplash.com/premium_photo-167872...
13    https://images.unsplash.com/photo-158351260380...
14    https://images.unsplash.com/photo-158333713041...
15    https://images.unsplash.com/photo-147788421336...
16    https://plus.unsplash.com/premium_photo-166629...
17    https://images.unsplash.com/photo-15762018

In [19]:
dog['image'][0]

'https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww'

In [20]:
for images in dog['image']:
    print(images)
    

https://plus.unsplash.com/premium_photo-1677542200557-3c6856cc98b1?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9nfGVufDB8fDB8fHww
https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9nfGVufDB8fDB8fHww
https://images.unsplash.com/photo-1517849845537-4d257902454a?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZG9nfGVufDB8fDB8fHww
https://images.unsplash.com/photo-1552053831-71594a27632d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZG9nfGVufDB8fDB8fHww
https://plus.unsplash.com/premium_photo-1676479611993-05b0c9232f84?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZG9nfGVufDB8fDB8fHww
https://images.unsplash.com/photo-1561037404-61cd46aa615b?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZG9nfGVufDB8fDB8fHww
https://images.u

In [21]:
import urllib.request

In [31]:
url = 'https://images.unsplash.com/photo-1560807707-8cc77767d783?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D'
urllib.request.urlretrieve(url,f'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\dog20.jpg')

('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\dog20.jpg',
 <http.client.HTTPMessage at 0x1e0b411f4d0>)

In [22]:
import os
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon'

In [23]:
os.mkdir('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder')

In [25]:
os.listdir()

['.ipynb_checkpoints',
 'Animals Folder',
 'Ass-4, Finder Data.ipynb',
 'Assignment- 3 IMAGE DATA COLLECTION.ipynb',
 'Data Collection and source of collection and their format.ipynb',
 'Folder',
 'Image data to Data Frame.ipynb',
 'Image Data to DataFrame',
 'Image Data.ipynb',
 'img_folder',
 'merged file of restauarants.csv',
 'top 30 restuarants in Mancherial',
 'Video data.ipynb']

In [26]:
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon'

In [28]:
os.chdir('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder')

In [29]:
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder'

In [32]:
n=0
for images in dog['image']:
    urllib.request.urlretrieve(url,f'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\dog{n}.jpg')
    n=n+1

In [33]:
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder'

In [34]:
os.mkdir('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cat')

In [35]:
os.mkdir('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Elephant')

In [36]:
os.mkdir('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Parrot')

In [37]:
os.mkdir('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cow')

In [38]:
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder'

In [40]:
os.listdir()

['Cat', 'Cow', 'Dog', 'Elephant', 'Parrot']

In [42]:
cat

image  \
0   https://plus.unsplash.com/premium_photo-167710...   
1   https://images.unsplash.com/photo-151488828697...   
2   https://images.unsplash.com/photo-157386552673...   
3   https://images.unsplash.com/photo-149536001054...   
4   https://plus.unsplash.com/premium_photo-167518...   
5   https://images.unsplash.com/photo-1533738363-b...   
6   https://images.unsplash.com/photo-161882641164...   
7   https://images.unsplash.com/photo-152633602417...   
8   https://plus.unsplash.com/premium_photo-168203...   
9   https://images.unsplash.com/photo-159219499630...   
10  https://images.unsplash.com/photo-159685440794...   
11  https://images.unsplash.com/photo-1561948955-5...   
12  https://plus.unsplash.com/premium_photo-167396...   
13  https://images.unsplash.com/photo-151905253707...   
14  https://images.unsplash.com/photo-152977887392...   
15  https://images.unsplash.com/photo-1543852786-1...   
16  https://plus.unsplash.com/premium_photo-167754...   
17  https://images.unsplash.com/photo-157415862268...   
18  https://images.unsplash.com/photo-149425699760...   
19  https://images.unsplash.com/photo-147809871161...   

                                                   by                source  \
0   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
1                 https://unsplash.com/@madhatterzone  https://unsplash.com   
2                        https://unsplash.com/@sadmax  https://unsplash.com   
3                 https://unsplash.com/@alxndr_london  https://unsplash.com   
4   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
5                    https://unsplash.com/@raouldroog  https://unsplash.com   
6                       https://unsplash.com/@bogdanf  https://unsplash.com   
7                      https://unsplash.com/@_k_arinn  https://unsplash.com   
8   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
9                      https://unsplash.com/@alvannee  https://unsplash.com   
10                    https://unsplash.com/@kabofoods  https://unsplash.com   
11                      https://unsplash.com/@niuhang  https://unsplash.com   
12  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
13               https://unsplash.com/@michaelsum1228  https://unsplash.com   
14                    https://unsplash.com/@e_d_g_a_r  https://unsplash.com   
15                   https://unsplash.com/@jaehunpark  https://unsplash.com   
16  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
17           https://unsplash.com/@cedric_photography  https://unsplash.com   
18                https://unsplash.com/@miklevasilyev  https://unsplash.com   
19                  https://unsplash.com/@pactovisual  https://unsplash.com   

                                        diffrentSizes  \
0   [https://plus.unsplash.com/premium_photo-16771...   
1   [https://images.unsplash.com/photo-15148882869...   
2   [https://images.unsplash.com/photo-15738655267...   
3   [https://images.unsplash.com/photo-14953600105...   
4   [https://plus.unsplash.com/premium_photo-16751...   
5   [https://images.unsplash.com/photo-1533738363-...   
6   [https://images.unsplash.com/photo-16188264116...   
7   [https://images.unsplash.com/photo-15263360241...   
8   [https://plus.unsplash.com/premium_photo-16820...   
9   [https://images.unsplash.com/photo-15921949963...   
10  [https://images.unsplash.com/photo-15968544079...   
11  [https://images.unsplash.com/photo-1561948955-...   
12  [https://plus.unsplash.com/premium_photo-16739...   
13  [https://images.unsplash.com/photo-15190525370...   
14  [https://images.unsplash.com/photo-15297788739...   
15  [https://images.unsplash.com/photo-1543852786-...   
16  [https://plus.unsplash.com/premium_photo-16775...   
17  [https://images.unsplash.com/photo-15741586226...   
18  [https://images.unsplash.com/photo-14942569976...   
19  [https://images.unsplash.com/photo-14780987116

In [43]:
Cat = cat

In [44]:
Cat

image  \
0   https://plus.unsplash.com/premium_photo-167710...   
1   https://images.unsplash.com/photo-151488828697...   
2   https://images.unsplash.com/photo-157386552673...   
3   https://images.unsplash.com/photo-149536001054...   
4   https://plus.unsplash.com/premium_photo-167518...   
5   https://images.unsplash.com/photo-1533738363-b...   
6   https://images.unsplash.com/photo-161882641164...   
7   https://images.unsplash.com/photo-152633602417...   
8   https://plus.unsplash.com/premium_photo-168203...   
9   https://images.unsplash.com/photo-159219499630...   
10  https://images.unsplash.com/photo-159685440794...   
11  https://images.unsplash.com/photo-1561948955-5...   
12  https://plus.unsplash.com/premium_photo-167396...   
13  https://images.unsplash.com/photo-151905253707...   
14  https://images.unsplash.com/photo-152977887392...   
15  https://images.unsplash.com/photo-1543852786-1...   
16  https://plus.unsplash.com/premium_photo-167754...   
17  https://images.unsplash.com/photo-157415862268...   
18  https://images.unsplash.com/photo-149425699760...   
19  https://images.unsplash.com/photo-147809871161...   

                                                   by                source  \
0   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
1                 https://unsplash.com/@madhatterzone  https://unsplash.com   
2                        https://unsplash.com/@sadmax  https://unsplash.com   
3                 https://unsplash.com/@alxndr_london  https://unsplash.com   
4   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
5                    https://unsplash.com/@raouldroog  https://unsplash.com   
6                       https://unsplash.com/@bogdanf  https://unsplash.com   
7                      https://unsplash.com/@_k_arinn  https://unsplash.com   
8   https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
9                      https://unsplash.com/@alvannee  https://unsplash.com   
10                    https://unsplash.com/@kabofoods  https://unsplash.com   
11                      https://unsplash.com/@niuhang  https://unsplash.com   
12  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
13               https://unsplash.com/@michaelsum1228  https://unsplash.com   
14                    https://unsplash.com/@e_d_g_a_r  https://unsplash.com   
15                   https://unsplash.com/@jaehunpark  https://unsplash.com   
16  https://unsplash.com/plus?referrer=%2Fphotos%2...  https://unsplash.com   
17           https://unsplash.com/@cedric_photography  https://unsplash.com   
18                https://unsplash.com/@miklevasilyev  https://unsplash.com   
19                  https://unsplash.com/@pactovisual  https://unsplash.com   

                                        diffrentSizes  \
0   [https://plus.unsplash.com/premium_photo-16771...   
1   [https://images.unsplash.com/photo-15148882869...   
2   [https://images.unsplash.com/photo-15738655267...   
3   [https://images.unsplash.com/photo-14953600105...   
4   [https://plus.unsplash.com/premium_photo-16751...   
5   [https://images.unsplash.com/photo-1533738363-...   
6   [https://images.unsplash.com/photo-16188264116...   
7   [https://images.unsplash.com/photo-15263360241...   
8   [https://plus.unsplash.com/premium_photo-16820...   
9   [https://images.unsplash.com/photo-15921949963...   
10  [https://images.unsplash.com/photo-15968544079...   
11  [https://images.unsplash.com/photo-1561948955-...   
12  [https://plus.unsplash.com/premium_photo-16739...   
13  [https://images.unsplash.com/photo-15190525370...   
14  [https://images.unsplash.com/photo-15297788739...   
15  [https://images.unsplash.com/photo-1543852786-...   
16  [https://plus.unsplash.com/premium_photo-16775...   
17  [https://images.unsplash.com/photo-15741586226...   
18  [https://images.unsplash.com/photo-14942569976...   
19  [https://images.unsplash.com/photo-14780987116

In [49]:
Cat['image']

0     https://plus.unsplash.com/premium_photo-167710...
1     https://images.unsplash.com/photo-151488828697...
2     https://images.unsplash.com/photo-157386552673...
3     https://images.unsplash.com/photo-149536001054...
4     https://plus.unsplash.com/premium_photo-167518...
5     https://images.unsplash.com/photo-1533738363-b...
6     https://images.unsplash.com/photo-161882641164...
7     https://images.unsplash.com/photo-152633602417...
8     https://plus.unsplash.com/premium_photo-168203...
9     https://images.unsplash.com/photo-159219499630...
10    https://images.unsplash.com/photo-159685440794...
11    https://images.unsplash.com/photo-1561948955-5...
12    https://plus.unsplash.com/premium_photo-167396...
13    https://images.unsplash.com/photo-151905253707...
14    https://images.unsplash.com/photo-152977887392...
15    https://images.unsplash.com/photo-1543852786-1...
16    https://plus.unsplash.com/premium_photo-167754...
17    https://images.unsplash.com/photo-15741586

In [50]:
Cat['image'][0]

'https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0fGVufDB8fDB8fHww'

In [51]:
url_cat = 'https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0fGVufDB8fDB8fHww'
urllib.request.urlretrieve(url_cat,'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cat\\cat1.jpg')

('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cat\\cat1.jpg',
 <http.client.HTTPMessage at 0x1e0b59d9fd0>)

In [55]:
for images in Cat['image']:
    print(images)

https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2F0fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1573865526739-10659fec78a5?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2F0fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1495360010541-f48722b34f7d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2F0fGVufDB8fDB8fHww
https://plus.unsplash.com/premium_photo-1675188410128-08479b027489?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2F0fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2F0fGVufDB8fDB8fHww
https://image

In [59]:
n=0
for images in Cat['image']:
    urllib.request.urlretrieve(url_cat,f'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cat\\cat{n}.jpg')
    n+=1

In [61]:
## Extracting image urls for Elephant
elephant['image']

0     https://plus.unsplash.com/premium_photo-166667...
1     https://images.unsplash.com/photo-1557050543-4...
2     https://images.unsplash.com/photo-160348308022...
3     https://images.unsplash.com/photo-158185201710...
4     https://plus.unsplash.com/premium_photo-167509...
5     https://images.unsplash.com/photo-150514823089...
6     https://images.unsplash.com/photo-156476005577...
7     https://images.unsplash.com/photo-157424129865...
8     https://plus.unsplash.com/premium_photo-166974...
9     https://images.unsplash.com/photo-1557178985-8...
10    https://images.unsplash.com/photo-161095773504...
11    https://images.unsplash.com/photo-157518710589...
12    https://plus.unsplash.com/premium_photo-166669...
13    https://images.unsplash.com/photo-1544211412-2...
14    https://images.unsplash.com/photo-160532615296...
15    https://images.unsplash.com/photo-157993381752...
16    https://plus.unsplash.com/premium_photo-166974...
17    https://images.unsplash.com/photo-15783266

In [62]:
elephant['image'][0]

'https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D'

In [64]:
## by taking any one url's of 20 urls
url_ele = 'https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D'
urllib.request.urlretrieve(url_ele,'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Elephant\\ele1.jpg') # we can see in the Elephant that an ele1.jpg image extreacted by url

('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Elephant\\ele1.jpg',
 <http.client.HTTPMessage at 0x1e0b5a78710>)

In [70]:
## As extracetd ele1.jpg image, we need to extract other images to folder by the url's # so for that need for write for loop

for image_url in elephant['image']:
    print(image_url)

https://plus.unsplash.com/premium_photo-1666670060278-eef65a99ec09?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D
https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D
https://images.unsplash.com/photo-1603483080228-04f2313d9f10?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D
https://images.unsplash.com/photo-1581852017103-68ac65514cf7?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D
https://plus.unsplash.com/premium_photo-1675098496724-65e2d3a972b0?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZWxlcGhhbnR8ZW58MHx8MHx8fDA%3D
https://images.unsplash.com/photo-1505148230895-d9a785a555fa?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8

In [71]:
n=0
for image_url in elephant['image']:
    urllib.request.urlretrieve(url_ele,f'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Elephant\\ele{n}.jpg') 
    n+=1

In [73]:
## Extracting image urls for Parrot
parrot['image']


0     https://plus.unsplash.com/premium_photo-166967...
1     https://images.unsplash.com/photo-1552728089-5...
2     https://images.unsplash.com/photo-1555169062-0...
3     https://images.unsplash.com/photo-151182379498...
4     https://plus.unsplash.com/premium_photo-166620...
5     https://images.unsplash.com/photo-1544923408-7...
6     https://images.unsplash.com/photo-159208941646...
7     https://images.unsplash.com/photo-158979235111...
8     https://plus.unsplash.com/premium_photo-166723...
9     https://images.unsplash.com/photo-1554202218-0...
10    https://images.unsplash.com/photo-149999590910...
11    https://images.unsplash.com/photo-151281943272...
12    https://plus.unsplash.com/premium_photo-166677...
13    https://images.unsplash.com/photo-160482601091...
14    https://images.unsplash.com/photo-161690250940...
15    https://images.unsplash.com/photo-161202478295...
16    https://plus.unsplash.com/premium_photo-168563...
17    https://images.unsplash.com/photo-15867680

In [74]:
parrot['image'][0]

'https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFycm90fGVufDB8fDB8fHww'

In [76]:
## by taking any one url's of 20 urls
url = 'https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFycm90fGVufDB8fDB8fHww'
urllib.request.urlretrieve(url,'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Parrot\\par1.jpg')

('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Parrot\\par1.jpg',
 <http.client.HTTPMessage at 0x1e0b5a64ad0>)

In [78]:
## As extracetd par1.jpg image, we need to extract other images to folder by the url's # so for that need for write for loop

for image_urls in parrot['image']:
    print(image_urls)


https://plus.unsplash.com/premium_photo-1669673986444-3d8d63f74ab3?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFycm90fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1552728089-57bdde30beb3?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFycm90fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1555169062-013468b47731?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cGFycm90fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1511823794984-b87716139b88?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGFycm90fGVufDB8fDB8fHww
https://plus.unsplash.com/premium_photo-1666201831967-93d3328416bb?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8cGFycm90fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1544923408-75c5cef46f14?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGFycm90fGVufDB8fDB8

In [79]:
n=1
for image_urls in parrot['image']:
    urllib.request.urlretrieve(url,f'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Parrot\\par{n}.jpg')
    n+=1
    

In [85]:
## Extracting image urls for Cow
cow['image']
for i in cow["image"]:
    print(i)

https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1546445317-29f4545e9d53?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1502590464431-3b66d77494d7?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y293fGVufDB8fDB8fHww
https://plus.unsplash.com/premium_photo-1677850457281-772c39419991?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y293fGVufDB8fDB8fHww
https://image

In [82]:
cow['image'][0]

'https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww'

In [88]:
url = 'https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww'

urllib.request.urlretrieve(url,'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cow\\cow1.jpg')


('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cow\\cow1.jpg',
 <http.client.HTTPMessage at 0x1e0b5aea510>)

In [89]:
for images in cow['image']:
    print(images)

https://plus.unsplash.com/premium_photo-1661962510497-9505129083fa?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1546445317-29f4545e9d53?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1502590464431-3b66d77494d7?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y293fGVufDB8fDB8fHww
https://plus.unsplash.com/premium_photo-1677850457281-772c39419991?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y293fGVufDB8fDB8fHww
https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y293fGVufDB8fDB8fHww
https://image

In [90]:
n=1
for images in cow['image']:
    urllib.request.urlretrieve(url,f'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder\\Cow\\cow{n}.jpg')
    n+=1
    

    

In [91]:
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Animals Folder'

In [92]:
os.listdir()

['Cat', 'Cow', 'Dog', 'Elephant', 'Parrot']

In [93]:
for folder in os.listdir():
    print(folder)

Cat
Cow
Dog
Elephant
Parrot


In [98]:
list_variales = []
class_var = []
c=1
for folder in os.listdir():
    for images in os.listdir(os.getcwd()+"\\{}".format(folder)):
        img = cv2.imread(os.getcwd()+"\\{}\\{}".format(folder,images),0)
        img = cv2.resize(img, (50,50))
        list_variales.append(img.flatten())
        class_var.append(folder)
        c+=1

In [99]:
list_variales

[array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 119, 117, ...,  16,  12,   5], dtype=uint8),
 array([116, 1

In [102]:
class_var

['Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cat',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Cow',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Dog',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Elephant',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot',
 'Parrot']

In [103]:
import pandas as pd

In [105]:
Df = pd.DataFrame(list_variales)

In [106]:
Df['class_var'] = pd.Series(class_var)

In [107]:
Df

0    1    2    3    4    5    6    7    8    9  ...  2491  2492  2493  \
0    116  119  117  120  143  137  136  144  148  139  ...    16    39    49   
1    116  119  117  120  143  137  136  144  148  139  ...    16    39    49   
2    116  119  117  120  143  137  136  144  148  139  ...    16    39    49   
3    116  119  117  120  143  137  136  144  148  139  ...    16    39    49   
4    116  119  117  120  143  137  136  144  148  139  ...    16    39    49   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
96    83   99   40  118  155   46   46   55   63   49  ...   115   104    84   
97    83   99   40  118  155   46   46   55   63   49  ...   115   104    84   
98    83   99   40  118  155   46   46   55   63   49  ...   115   104    84   
99    83   99   40  118  155   46   46   55   63   49  ...   115   104    84   
100   83   99   40  118  155   46   46   55   63   49  ...   115   104    84   

     2494  2495  2496  2497  2498  2499  class_var  
0      20    15    15    16    12     5        Cat  
1      20    15    15    16    12     5        Cat  
2      20    15    15    16    12     5        Cat  
3      20    15    15    16    12     5        Cat  
4      20    15    15    16    12     5        Cat  
..    ...   ...   ...   ...   ...   ...        ...  
96     87    99    90    91    42    44     Parrot  
97     87    99    90    91    42    44     Parrot  
98     87    99    90    91    42    44     Parrot  
99     87    99    90    91    42    44     Parrot  
100    87    99    90    91    42    44     Parrot  

[101 rows x 2501 columns]