In [1]:
import cv2

In [3]:
import numpy as np

In [4]:
import os

In [5]:
os.mkdir(r"C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder")

In [13]:
os.mkdir(r"C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder\\One")

In [14]:
os.mkdir(r"C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder\\Two")

In [15]:
os.mkdir(r"C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder\\THree")

In [16]:
os.mkdir(r"C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder\\Four")

In [17]:
os.mkdir(r"C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder\\Five")

In [25]:
video = cv2.VideoCapture(0)
count=1

while True:
    success,image = video.read()
    if success==False:
        break
    cv2.imshow('video',image)
    #if count%10==0:
    cv2.imwrite('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder\\frame{}.jpg'.format(count),image)
    count+=1
    if cv2.waitKey(1) & 255 == ord('a'):
        break
cv2.destroyAllWindows()

In [26]:
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon'

In [27]:
os.chdir('C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder')

In [28]:
os.getcwd()

'C:\\Users\\GOLLA RAVI TEJA\\Downloads\\MY NOTEBOOK FOLDER\\ML by Saxon\\Folder'

In [30]:
os.listdir()

['Five', 'Four', 'One', 'Three', 'Two']

In [32]:
for folder in os.listdir():
    print(folder)

Five
Four
One
Three
Two


In [39]:
list_images = []
class_var = []
c=1
for folder in os.listdir():
    for images in os.listdir(os.getcwd()+"\\{}".format(folder)):
        img = cv2.imread(os.getcwd()+"\\{}\\{}".format(folder,images),0)
        img = cv2.resize(img,(50,50))
        list_images.append(img.flatten())
        class_var.append(folder)
        c=c+1 # c+=1
        

In [40]:
list_images

[array([177, 173, 171, ..., 167, 165, 166], dtype=uint8),
 array([180, 179, 178, ..., 173, 172, 171], dtype=uint8),
 array([184, 183, 181, ..., 180, 180, 180], dtype=uint8),
 array([181, 179, 179, ..., 173, 172, 171], dtype=uint8),
 array([180, 179, 179, ..., 174, 173, 172], dtype=uint8),
 array([181, 180, 179, ..., 174, 173, 173], dtype=uint8),
 array([181, 180, 178, ..., 173, 173, 173], dtype=uint8),
 array([181, 180, 179, ..., 174, 173, 173], dtype=uint8),
 array([181, 180, 179, ..., 175, 174, 173], dtype=uint8),
 array([181, 180, 179, ..., 175, 174, 174], dtype=uint8),
 array([182, 180, 179, ..., 176, 176, 174], dtype=uint8),
 array([181, 181, 179, ..., 175, 175, 174], dtype=uint8),
 array([176, 174, 173, ..., 167, 166, 165], dtype=uint8),
 array([182, 181, 179, ..., 176, 175, 175], dtype=uint8),
 array([181, 180, 179, ..., 176, 177, 176], dtype=uint8),
 array([183, 181, 179, ..., 176, 177, 175], dtype=uint8),
 array([183, 181, 180, ..., 176, 177, 176], dtype=uint8),
 array([183, 1

In [41]:
class_var

['Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Five',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 'Four',
 

In [42]:
import pandas as pd

In [44]:
Data = pd.DataFrame(list_images)

In [46]:
Data["class_var"] = pd.Series(class_var)

In [47]:
Data

0    1    2    3    4    5    6    7    8    9  ...  2491  2492  2493  \
0    177  173  171  171  171  170  168  167  166  166  ...   178   172   169   
1    180  179  178  178  177  174  175  174  171  171  ...   184   178   176   
2    184  183  181  181  180  180  180  179  178  179  ...   191   185   184   
3    181  179  179  177  177  175  176  175  172  171  ...   185   178   176   
4    180  179  179  178  176  175  176  175  171  172  ...   185   178   177   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
494  179  177  176  174  169  165  141  133  134  132  ...   180   176   171   
495  179  178  177  174  171  165  142  132  132  131  ...   180   175   172   
496  180  179  178  174  171  164  142  133  134  133  ...   179   176   173   
497  179  180  178  174  172  166  143  134  133  132  ...   180   177   173   
498  181  180  178  175  172  167  144  135  134  133  ...   181   178   175   

     2494  2495  2496  2497  2498  2499  class_var  
0     169   167   166   167   165   166       Five  
1     175   173   173   173   172   171       Five  
2     182   183   181   180   180   180       Five  
3     174   174   173   173   172   171       Five  
4     175   176   175   174   173   172       Five  
..    ...   ...   ...   ...   ...   ...        ...  
494   167   163   160   158   155   154        Two  
495   167   164   160   158   156   155        Two  
496   168   163   161   158   157   154        Two  
497   169   164   161   159   158   156        Two  
498   169   165   161   159   158   156        Two  

[499 rows x 2501 columns]

In [48]:
Data['class_var'].value_counts()

class_var
Five     100
Four     100
One      100
Two      100
Three     99
Name: count, dtype: int64